// Generated reviewed AST shapes. See scripts/Generate-PropShapes.py.
const INVULNERABLE: &[Shape] = &[
    Shape {
        opcode: 7,
        start: 0,
        end: 11,
        serialized: 0,
        children: 1,
        operand: ExpectedOperand::Target(21),
    },
    Shape {
        opcode: 151,
        start: 3,
        end: 11,
        serialized: 3,
        children: 3,
        operand: ExpectedOperand::Native(151),
    },
    Shape {
        opcode: 1,
        start: 4,
        end: 9,
        serialized: 4,
        children: 0,
        operand: ExpectedOperand::Object(11724, "Prop.Health"),
    },
    Shape {
        opcode: 37,
        start: 9,
        end: 10,
        serialized: 8,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 22,
        start: 10,
        end: 11,
        serialized: 9,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 113,
        start: 11,
        end: 18,
        serialized: 10,
        children: 2,
        operand: ExpectedOperand::Native(113),
    },
    Shape {
        opcode: 33,
        start: 12,
        end: 17,
        serialized: 11,
        children: 0,
        operand: ExpectedOperand::Name("Damagable"),
    },
    Shape {
        opcode: 22,
        start: 17,
        end: 18,
        serialized: 14,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 6,
        start: 18,
        end: 21,
        serialized: 15,
        children: 0,
        operand: ExpectedOperand::Target(82),
    },
    Shape {
        opcode: 7,
        start: 21,
        end: 30,
        serialized: 18,
        children: 1,
        operand: ExpectedOperand::Target(82),
    },
    Shape {
        opcode: 45,
        start: 24,
        end: 30,
        serialized: 21,
        children: 1,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 1,
        start: 25,
        end: 30,
        serialized: 22,
        children: 0,
        operand: ExpectedOperand::Object(11737, "Prop.bDisplayStateMessages"),
    },
    Shape {
        opcode: 25,
        start: 30,
        end: 82,
        serialized: 26,
        children: 2,
        operand: ExpectedOperand::Context(34, 0),
    },
    Shape {
        opcode: 25,
        start: 31,
        end: 45,
        serialized: 27,
        children: 2,
        operand: ExpectedOperand::Context(5, 4),
    },
    Shape {
        opcode: 1,
        start: 32,
        end: 37,
        serialized: 28,
        children: 0,
        operand: ExpectedOperand::Object(1349, "Actor.Level"),
    },
    Shape {
        opcode: 1,
        start: 40,
        end: 45,
        serialized: 34,
        children: 0,
        operand: ExpectedOperand::Object(4126, "LevelInfo.Game"),
    },
    Shape {
        opcode: 27,
        start: 48,
        end: 82,
        serialized: 40,
        children: 3,
        operand: ExpectedOperand::Name("Broadcast"),
    },
    Shape {
        opcode: 23,
        start: 53,
        end: 54,
        serialized: 43,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 112,
        start: 54,
        end: 81,
        serialized: 44,
        children: 3,
        operand: ExpectedOperand::Native(112),
    },
    Shape {
        opcode: 112,
        start: 55,
        end: 62,
        serialized: 45,
        children: 3,
        operand: ExpectedOperand::Native(112),
    },
    Shape {
        opcode: 31,
        start: 56,
        end: 58,
        serialized: 46,
        children: 0,
        operand: ExpectedOperand::String(""),
    },
    Shape {
        opcode: 57,
        start: 58,
        end: 61,
        serialized: 48,
        children: 1,
        operand: ExpectedOperand::Byte(86),
    },
    Shape {
        opcode: 23,
        start: 60,
        end: 61,
        serialized: 50,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 22,
        start: 61,
        end: 62,
        serialized: 51,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 31,
        start: 62,
        end: 80,
        serialized: 52,
        children: 0,
        operand: ExpectedOperand::String(" Is Invulnerable"),
    },
    Shape {
        opcode: 22,
        start: 80,
        end: 81,
        serialized: 70,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 22,
        start: 81,
        end: 82,
        serialized: 71,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 4,
        start: 82,
        end: 84,
        serialized: 72,
        children: 1,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 11,
        start: 83,
        end: 84,
        serialized: 73,
        children: 0,
        operand: ExpectedOperand::None,
    },
];
const DAMAGABLE: &[Shape] = &[
    Shape {
        opcode: 7,
        start: 0,
        end: 9,
        serialized: 0,
        children: 1,
        operand: ExpectedOperand::Target(58),
    },
    Shape {
        opcode: 45,
        start: 3,
        end: 9,
        serialized: 3,
        children: 1,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 1,
        start: 4,
        end: 9,
        serialized: 4,
        children: 0,
        operand: ExpectedOperand::Object(11737, "Prop.bDisplayStateMessages"),
    },
    Shape {
        opcode: 25,
        start: 9,
        end: 58,
        serialized: 8,
        children: 2,
        operand: ExpectedOperand::Context(31, 0),
    },
    Shape {
        opcode: 25,
        start: 10,
        end: 24,
        serialized: 9,
        children: 2,
        operand: ExpectedOperand::Context(5, 4),
    },
    Shape {
        opcode: 1,
        start: 11,
        end: 16,
        serialized: 10,
        children: 0,
        operand: ExpectedOperand::Object(1349, "Actor.Level"),
    },
    Shape {
        opcode: 1,
        start: 19,
        end: 24,
        serialized: 16,
        children: 0,
        operand: ExpectedOperand::Object(4126, "LevelInfo.Game"),
    },
    Shape {
        opcode: 27,
        start: 27,
        end: 58,
        serialized: 22,
        children: 3,
        operand: ExpectedOperand::Name("Broadcast"),
    },
    Shape {
        opcode: 23,
        start: 32,
        end: 33,
        serialized: 25,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 112,
        start: 33,
        end: 57,
        serialized: 26,
        children: 3,
        operand: ExpectedOperand::Native(112),
    },
    Shape {
        opcode: 112,
        start: 34,
        end: 41,
        serialized: 27,
        children: 3,
        operand: ExpectedOperand::Native(112),
    },
    Shape {
        opcode: 31,
        start: 35,
        end: 37,
        serialized: 28,
        children: 0,
        operand: ExpectedOperand::String(""),
    },
    Shape {
        opcode: 57,
        start: 37,
        end: 40,
        serialized: 30,
        children: 1,
        operand: ExpectedOperand::Byte(86),
    },
    Shape {
        opcode: 23,
        start: 39,
        end: 40,
        serialized: 32,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 22,
        start: 40,
        end: 41,
        serialized: 33,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 31,
        start: 41,
        end: 56,
        serialized: 34,
        children: 0,
        operand: ExpectedOperand::String(" Is Damagable"),
    },
    Shape {
        opcode: 22,
        start: 56,
        end: 57,
        serialized: 49,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 22,
        start: 57,
        end: 58,
        serialized: 50,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 4,
        start: 58,
        end: 60,
        serialized: 51,
        children: 1,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 11,
        start: 59,
        end: 60,
        serialized: 52,
        children: 0,
        operand: ExpectedOperand::None,
    },
];
const ANIM_INVULNERABLE: &[Shape] = &[
    Shape {
        opcode: 28,
        start: 0,
        end: 6,
        serialized: 0,
        children: 1,
        operand: ExpectedOperand::Object(11676, "Prop.Invulnerable.BeginState"),
    },
    Shape {
        opcode: 22,
        start: 5,
        end: 6,
        serialized: 4,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 7,
        start: 6,
        end: 26,
        serialized: 5,
        children: 1,
        operand: ExpectedOperand::Target(69),
    },
    Shape {
        opcode: 255,
        start: 9,
        end: 26,
        serialized: 8,
        children: 3,
        operand: ExpectedOperand::Native(255),
    },
    Shape {
        opcode: 54,
        start: 10,
        end: 20,
        serialized: 9,
        children: 1,
        operand: ExpectedOperand::Object(11831, "AnimProp.PropAnimInfo.Anim"),
    },
    Shape {
        opcode: 1,
        start: 15,
        end: 20,
        serialized: 13,
        children: 0,
        operand: ExpectedOperand::Object(11845, "AnimProp.AnimHealthy"),
    },
    Shape {
        opcode: 33,
        start: 20,
        end: 25,
        serialized: 17,
        children: 0,
        operand: ExpectedOperand::Name("None"),
    },
    Shape {
        opcode: 22,
        start: 25,
        end: 26,
        serialized: 19,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 7,
        start: 26,
        end: 40,
        serialized: 20,
        children: 1,
        operand: ExpectedOperand::Target(56),
    },
    Shape {
        opcode: 45,
        start: 29,
        end: 40,
        serialized: 23,
        children: 1,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 54,
        start: 30,
        end: 40,
        serialized: 24,
        children: 1,
        operand: ExpectedOperand::Object(11832, "AnimProp.PropAnimInfo.bLoop"),
    },
    Shape {
        opcode: 1,
        start: 35,
        end: 40,
        serialized: 28,
        children: 0,
        operand: ExpectedOperand::Object(11845, "AnimProp.AnimHealthy"),
    },
    Shape {
        opcode: 97,
        start: 40,
        end: 53,
        serialized: 32,
        children: 2,
        operand: ExpectedOperand::Native(260),
    },
    Shape {
        opcode: 54,
        start: 42,
        end: 52,
        serialized: 34,
        children: 1,
        operand: ExpectedOperand::Object(11831, "AnimProp.PropAnimInfo.Anim"),
    },
    Shape {
        opcode: 1,
        start: 47,
        end: 52,
        serialized: 38,
        children: 0,
        operand: ExpectedOperand::Object(11845, "AnimProp.AnimHealthy"),
    },
    Shape {
        opcode: 22,
        start: 52,
        end: 53,
        serialized: 42,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 6,
        start: 53,
        end: 56,
        serialized: 43,
        children: 0,
        operand: ExpectedOperand::Target(69),
    },
    Shape {
        opcode: 97,
        start: 56,
        end: 69,
        serialized: 46,
        children: 2,
        operand: ExpectedOperand::Native(259),
    },
    Shape {
        opcode: 54,
        start: 58,
        end: 68,
        serialized: 48,
        children: 1,
        operand: ExpectedOperand::Object(11831, "AnimProp.PropAnimInfo.Anim"),
    },
    Shape {
        opcode: 1,
        start: 63,
        end: 68,
        serialized: 52,
        children: 0,
        operand: ExpectedOperand::Object(11845, "AnimProp.AnimHealthy"),
    },
    Shape {
        opcode: 22,
        start: 68,
        end: 69,
        serialized: 56,
        children: 0,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 4,
        start: 69,
        end: 71,
        serialized: 57,
        children: 1,
        operand: ExpectedOperand::None,
    },
    Shape {
        opcode: 11,
        start: 70,
        end: 71,
        serialized: 58,
        children: 0,
        operand: ExpectedOperand::None,
    },
];
