"""Generate two scalar expression kernels from reviewed original director ASM."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
code=[]
for line in (root/'analysis/decompiled/skeletal-director.asm').read_text().splitlines():
    if not line or line.startswith('#'):continue
    address,instruction=line.split(' ',1);opcode,_,args=instruction.partition(' ');code.append((int(address,16),opcode,args))
def offset(op):
    words=re.findall(r'0x[0-9a-f]+',op);return int(words[-1],16) if words else 0
def kernel(ancestor):
    registers={};stack={};gpr={};memory={};base=0
    for address,opcode,args in code:
        if not (0x10502921<=address<=0x10502c84 if ancestor else 0x105022fb<=address<=0x1050276f):continue
        def operand(op):
            if op.startswith('XMM'):return registers[op]
            off=offset(op)
            if 'ESP' in op:
                first=0x20 if ancestor else 0x80
                if first<=off<first+64:return f'd[{(off-first)//4}]'
                return stack[off]
            if 'EBP' in op:return f'm[{off//4}]'
            if 'EAX' in op:
                index=((0 if 'ESI' in op else base)+off)//4
                return memory.get(index,f'm[{index}]')
            raise AssertionError(op)
        if ancestor and opcode=='MOV' and args=='EAX,dword ptr [ECX + 0xa0]':base=0;continue
        if ancestor and opcode=='LEA' and args.startswith('EAX,[EAX + ESI'):base=offset(args);continue
        if opcode=='MOV' and ancestor:
            dst,src=args.split(',',1)
            if src.startswith('dword ptr [ESP'):gpr[dst]=operand(src)
            elif dst.startswith('dword ptr [EAX'):memory[(base+offset(dst))//4]=gpr[src]
            continue
        if opcode not in ('MOVSS','MOVAPS','ADDSS','MULSS'):continue
        dst,src=args.split(',',1)
        if dst.startswith('XMM'):
            expr=operand(src)
            registers[dst]=expr if opcode in ('MOVSS','MOVAPS') else f'({registers[dst]} '+('+' if opcode=='ADDSS' else '*')+f' {expr})'
        else:assert opcode=='MOVSS' and 'ESP' in dst;stack[offset(dst)]=operand(src)
    if ancestor:
        assert set(memory)==set(range(12));return [memory.get(i,f'm[{i}]') for i in range(16)]
    assert all(off in stack for off in range(0xd4,0x114,4));return [stack[off] for off in range(0xd4,0x114,4)]
lines=['//! Original scalar SSE director product kernels. Generated by Generate-DirectorProducts.py.']
for ancestor,name in [(False,'compose_relative_director'),(True,'correct_ancestor_rows')]:
    expressions=kernel(ancestor)
    lines += [f'pub fn {name}(current:[u32;16], director:[u32;16])->[u32;16] {{','    let m=current.map(f32::from_bits);','    let d=director.map(f32::from_bits);','    [']
    lines += ['        '+expr+',' for expr in expressions]
    lines += ['    ].map(f32::to_bits)','}']
(root/'crates/rc-package/src/skeletal_director_products.rs').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('16 relative outputs and 12 corrected ancestor row components translated')
