"""Translate reviewed scalar SSE arithmetic of core 10143b40 into explicit f32 SSA."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
registers={};stack={};output=[];serial=0
lines=['//! FMatrix::Inverse (core 10143b40), explicit original scalar SSE operation order.',
       '//! Generated by scripts/Generate-MatrixInverse.py from the archived ASM.',
       'pub fn inverse_matrix(input: [u32; 16]) -> [u32; 16] {','    let m = input.map(f32::from_bits);']
def offset(op):
    words=re.findall(r'0x[0-9a-f]+',op);return int(words[-1],16) if words else 0
def operand(op):
    if op.startswith('XMM'):return registers[op]
    if 'ECX' in op:return f'm[{offset(op)//4}]'
    if 'ESP' in op:return stack[offset(op)]
    assert op=='dword ptr [0x10186c18]',op
    return '1.0f32'
for line in (root/'analysis/decompiled/skeletal-matrix-inverse.asm').read_text().splitlines():
    if not line or line.startswith('#'):continue
    address,instruction=line.split(' ',1);address=int(address,16)
    if address==0x10143c65:
        lines+=['    // Native equality excludes unordered; exact zero returns the global Identity.',f'    if {registers["XMM1"]} == 0.0 {{','        return [1f32.to_bits(),0,0,0,0,1f32.to_bits(),0,0,0,0,1f32.to_bits(),0,0,0,0,1f32.to_bits()];','    }']
    opcode,_,args=instruction.partition(' ')
    if opcode not in ('MOVSS','MOVAPS','XORPS','ADDSS','SUBSS','MULSS','DIVSS'):continue
    dst,src=args.split(',',1)
    if dst.startswith('XMM'):
        if opcode=='XORPS':assert dst==src;expression='0.0f32'
        else:
            expression=operand(src)
            if opcode not in ('MOVSS','MOVAPS'):expression=f'{registers[dst]} '+{'ADDSS':'+','SUBSS':'-','MULSS':'*','DIVSS':'/'}[opcode]+' '+expression
        name=f'v{serial}';serial+=1;lines.append(f'    let {name} = {expression}; // {address:08x}');registers[dst]=name
    else:
        assert opcode=='MOVSS' and 'ESP' in dst;stack[offset(dst)]=operand(src)
assert all(i in stack for i in range(0x14,0x54,4))
lines+=['    ['+', '.join(stack[i] for i in range(0x14,0x54,4))+'].map(f32::to_bits)','}', '#[cfg(test)]', '#[path = "skeletal_matrix_inverse_tests.rs"]', 'mod tests;']
(root/'crates/rc-package/src/skeletal_matrix_inverse.rs').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(f'{serial} original scalar register assignments translated')
