//! Offline relocated scalar SSE arithmetic; no original DLL execution or live scene.
use std::{env, fs, convert::TryInto};
unsafe fn world_screen(state: &[u32; 60], scratch: &mut [u32; 384]) {
    unsafe { core::arch::asm!(
        "movss xmm0, dword ptr [r8 + 204]",
        "mulss xmm0, dword ptr [r8 + 116]",
        "movss xmm1, dword ptr [r8 + 188]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 108]",
        "mulss xmm1, dword ptr [r8 + 172]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 120]",
        "mulss xmm1, dword ptr [r8 + 220]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 192]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "movss dword ptr [r9 + 640], xmm0",
        "movss xmm0, dword ptr [r8 + 224]",
        "mulss xmm0, dword ptr [r8 + 120]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 176]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 208]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 196]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "movss dword ptr [r9 + 644], xmm0",
        "movss xmm0, dword ptr [r8 + 120]",
        "mulss xmm0, dword ptr [r8 + 228]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 180]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 212]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 216]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "movss dword ptr [r9 + 648], xmm0",
        "movss xmm0, dword ptr [r8 + 108]",
        "mulss xmm0, dword ptr [r8 + 184]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 232]",
        "mulss xmm1, dword ptr [r8 + 120]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 200]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 220]",
        "movss dword ptr [r9 + 652], xmm0",
        "movss xmm0, dword ptr [r8 + 204]",
        "mulss xmm0, dword ptr [r8 + 132]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 188]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 124]",
        "mulss xmm1, dword ptr [r8 + 172]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 128]",
        "mulss xmm1, dword ptr [r8 + 192]",
        "movss dword ptr [r9 + 656], xmm0",
        "movss xmm0, dword ptr [r8 + 176]",
        "mulss xmm0, dword ptr [r8 + 124]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 224]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 132]",
        "mulss xmm1, dword ptr [r8 + 208]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 228]",
        "movss dword ptr [r9 + 660], xmm0",
        "movss xmm0, dword ptr [r8 + 180]",
        "mulss xmm0, dword ptr [r8 + 124]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 132]",
        "mulss xmm1, dword ptr [r8 + 212]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 128]",
        "mulss xmm1, dword ptr [r8 + 196]",
        "addss xmm0, xmm1",
        "movss dword ptr [r9 + 664], xmm0",
        "movss xmm0, dword ptr [r8 + 232]",
        "mulss xmm0, dword ptr [r8 + 136]",
        "movss xmm1, dword ptr [r8 + 216]",
        "mulss xmm1, dword ptr [r8 + 132]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 128]",
        "mulss xmm1, dword ptr [r8 + 200]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 184]",
        "mulss xmm1, dword ptr [r8 + 124]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 220]",
        "movss dword ptr [r9 + 668], xmm0",
        "movss xmm0, dword ptr [r8 + 204]",
        "mulss xmm0, dword ptr [r8 + 148]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 188]",
        "mulss xmm1, dword ptr [r8 + 144]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 172]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 144]",
        "mulss xmm1, dword ptr [r8 + 192]",
        "movss dword ptr [r9 + 672], xmm0",
        "movss xmm0, dword ptr [r8 + 176]",
        "mulss xmm0, dword ptr [r8 + 140]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 224]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 208]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 228]",
        "movss dword ptr [r9 + 676], xmm0",
        "movss xmm0, dword ptr [r8 + 180]",
        "mulss xmm0, dword ptr [r8 + 140]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 212]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 144]",
        "mulss xmm1, dword ptr [r8 + 196]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 216]",
        "mulss xmm1, dword ptr [r8 + 148]",
        "movss dword ptr [r9 + 680], xmm0",
        "movss xmm0, dword ptr [r8 + 232]",
        "mulss xmm0, dword ptr [r8 + 152]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 144]",
        "mulss xmm1, dword ptr [r8 + 200]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 184]",
        "mulss xmm1, dword ptr [r8 + 140]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 220]",
        "movss dword ptr [r9 + 684], xmm0",
        "movss xmm0, dword ptr [r8 + 204]",
        "mulss xmm0, dword ptr [r8 + 164]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 188]",
        "mulss xmm1, dword ptr [r8 + 160]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 156]",
        "mulss xmm1, dword ptr [r8 + 172]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 160]",
        "mulss xmm1, dword ptr [r8 + 192]",
        "movss dword ptr [r9 + 688], xmm0",
        "movss xmm0, dword ptr [r8 + 176]",
        "mulss xmm0, dword ptr [r8 + 156]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 224]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 164]",
        "mulss xmm1, dword ptr [r8 + 208]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 228]",
        "movss dword ptr [r9 + 692], xmm0",
        "movss xmm0, dword ptr [r8 + 180]",
        "mulss xmm0, dword ptr [r8 + 156]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 164]",
        "mulss xmm1, dword ptr [r8 + 212]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 160]",
        "mulss xmm1, dword ptr [r8 + 196]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 216]",
        "mulss xmm1, dword ptr [r8 + 164]",
        "movss dword ptr [r9 + 696], xmm0",
        "movss xmm0, dword ptr [r8 + 232]",
        "mulss xmm0, dword ptr [r8 + 168]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 160]",
        "mulss xmm1, dword ptr [r8 + 200]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 184]",
        "mulss xmm1, dword ptr [r8 + 156]",
        "addss xmm0, xmm1",
        "movss dword ptr [r9 + 700], xmm0",
        in("r8") state.as_ptr(), in("r9") scratch.as_mut_ptr(),
        out("xmm0") _,
        out("xmm1") _,
        out("xmm2") _,
        out("xmm3") _,
        out("xmm4") _,
        out("xmm5") _,
        out("xmm6") _,
        out("xmm7") _,
        options(nostack)
    ); }
}
unsafe fn object_screen_view(state: &[u32; 60], scratch: &mut [u32; 384]) {
    unsafe { core::arch::asm!(
        "movss xmm0, dword ptr [r8 + 56]",
        "mulss xmm0, dword ptr [r8 + 156]",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 52]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 124]",
        "mulss xmm1, dword ptr [r8 + 48]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 44]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 44]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "movss dword ptr [r9 + 768], xmm0",
        "movss xmm0, dword ptr [r8 + 56]",
        "mulss xmm0, dword ptr [r8 + 160]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 52]",
        "mulss xmm1, dword ptr [r8 + 144]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 48]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 48]",
        "mulss xmm1, dword ptr [r8 + 132]",
        "movss dword ptr [r9 + 772], xmm0",
        "movss xmm0, dword ptr [r8 + 148]",
        "mulss xmm0, dword ptr [r8 + 52]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 44]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 56]",
        "mulss xmm1, dword ptr [r8 + 164]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 44]",
        "mulss xmm1, dword ptr [r8 + 120]",
        "movss dword ptr [r9 + 776], xmm0",
        "movss xmm0, dword ptr [r8 + 56]",
        "mulss xmm0, dword ptr [r8 + 168]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 48]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 52]",
        "mulss xmm1, dword ptr [r8 + 152]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 60]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "movss dword ptr [r9 + 780], xmm0",
        "movss xmm0, dword ptr [r8 + 124]",
        "mulss xmm0, dword ptr [r8 + 64]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 68]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 72]",
        "mulss xmm1, dword ptr [r8 + 156]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 72]",
        "mulss xmm1, dword ptr [r8 + 160]",
        "movss dword ptr [r9 + 784], xmm0",
        "movss xmm0, dword ptr [r8 + 60]",
        "mulss xmm0, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 68]",
        "mulss xmm1, dword ptr [r8 + 144]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 64]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 164]",
        "mulss xmm1, dword ptr [r8 + 72]",
        "movss dword ptr [r9 + 788], xmm0",
        "movss xmm0, dword ptr [r8 + 64]",
        "mulss xmm0, dword ptr [r8 + 132]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 68]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 60]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss dword ptr [r9 + 792], xmm0",
        "movss xmm0, dword ptr [r8 + 60]",
        "mulss xmm0, dword ptr [r8 + 120]",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 64]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 72]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 68]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 76]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "movss dword ptr [r9 + 796], xmm0",
        "movss xmm0, dword ptr [r8 + 124]",
        "mulss xmm0, dword ptr [r8 + 80]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 84]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 88]",
        "mulss xmm1, dword ptr [r8 + 156]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 88]",
        "mulss xmm1, dword ptr [r8 + 160]",
        "movss dword ptr [r9 + 800], xmm0",
        "movss xmm0, dword ptr [r8 + 76]",
        "mulss xmm0, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 84]",
        "mulss xmm1, dword ptr [r8 + 144]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 80]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 164]",
        "mulss xmm1, dword ptr [r8 + 88]",
        "movss dword ptr [r9 + 804], xmm0",
        "movss xmm0, dword ptr [r8 + 80]",
        "mulss xmm0, dword ptr [r8 + 132]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 84]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 76]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 80]",
        "movss dword ptr [r9 + 808], xmm0",
        "movss xmm0, dword ptr [r8 + 76]",
        "mulss xmm0, dword ptr [r8 + 120]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 88]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 84]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 92]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "movss dword ptr [r9 + 812], xmm0",
        "movss xmm0, dword ptr [r8 + 124]",
        "mulss xmm0, dword ptr [r8 + 96]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 100]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 104]",
        "mulss xmm1, dword ptr [r8 + 156]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 104]",
        "mulss xmm1, dword ptr [r8 + 160]",
        "movss dword ptr [r9 + 816], xmm0",
        "movss xmm0, dword ptr [r8 + 92]",
        "mulss xmm0, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 100]",
        "mulss xmm1, dword ptr [r8 + 144]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 96]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 164]",
        "mulss xmm1, dword ptr [r8 + 104]",
        "movss dword ptr [r9 + 820], xmm0",
        "movss xmm0, dword ptr [r8 + 96]",
        "mulss xmm0, dword ptr [r8 + 132]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 100]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 92]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 96]",
        "movss dword ptr [r9 + 824], xmm0",
        "movss xmm0, dword ptr [r8 + 92]",
        "mulss xmm0, dword ptr [r8 + 120]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 104]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 100]",
        "addss xmm0, xmm1",
        "movss dword ptr [r9 + 828], xmm0",
        in("r8") state.as_ptr(), in("r9") scratch.as_mut_ptr(),
        out("xmm0") _,
        out("xmm1") _,
        out("xmm2") _,
        out("xmm3") _,
        out("xmm4") _,
        out("xmm5") _,
        out("xmm6") _,
        out("xmm7") _,
        options(nostack)
    ); }
}
unsafe fn object_screen_projection(state: &[u32; 60], scratch: &mut [u32; 384]) {
    unsafe { core::arch::asm!(
        "movss xmm1, dword ptr [r9 + 260]",
        "movss xmm2, dword ptr [r9 + 264]",
        "movaps xmm4, xmm1",
        "mulss xmm4, dword ptr [r8 + 16]",
        "movaps xmm0, xmm2",
        "mulss xmm0, dword ptr [r8 + 32]",
        "addss xmm4, xmm0",
        "movss xmm0, dword ptr [r9 + 256]",
        "movaps xmm3, xmm0",
        "mulss xmm3, dword ptr [r8 + 0]",
        "addss xmm4, xmm3",
        "movss xmm3, dword ptr [r9 + 268]",
        "movaps xmm5, xmm3",
        "mulss xmm5, dword ptr [r8 + 48]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 384], xmm4",
        "movss xmm4, dword ptr [r8 + 52]",
        "mulss xmm4, xmm3",
        "movaps xmm5, xmm0",
        "mulss xmm5, dword ptr [r8 + 4]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 20]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm2",
        "mulss xmm5, dword ptr [r8 + 36]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 388], xmm4",
        "movaps xmm5, xmm0",
        "mulss xmm5, dword ptr [r8 + 8]",
        "mulss xmm0, dword ptr [r8 + 12]",
        "movaps xmm4, xmm3",
        "mulss xmm4, dword ptr [r8 + 56]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 24]",
        "mulss xmm1, dword ptr [r8 + 28]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm2",
        "mulss xmm5, dword ptr [r8 + 40]",
        "mulss xmm2, dword ptr [r8 + 44]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 392], xmm4",
        "addss xmm0, xmm1",
        "mulss xmm3, dword ptr [r8 + 60]",
        "movss xmm1, dword ptr [r9 + 276]",
        "addss xmm0, xmm2",
        "addss xmm0, xmm3",
        "movss dword ptr [r9 + 396], xmm0",
        "movss xmm0, dword ptr [r9 + 272]",
        "movaps xmm4, xmm0",
        "mulss xmm4, dword ptr [r8 + 0]",
        "movaps xmm2, xmm1",
        "mulss xmm2, dword ptr [r8 + 16]",
        "addss xmm4, xmm2",
        "movss xmm2, dword ptr [r9 + 280]",
        "movaps xmm3, xmm2",
        "mulss xmm3, dword ptr [r8 + 32]",
        "addss xmm4, xmm3",
        "movss xmm3, dword ptr [r9 + 284]",
        "movaps xmm5, xmm3",
        "mulss xmm5, dword ptr [r8 + 48]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 400], xmm4",
        "movss xmm4, dword ptr [r8 + 52]",
        "mulss xmm4, xmm3",
        "movaps xmm5, xmm0",
        "mulss xmm5, dword ptr [r8 + 4]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 20]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm2",
        "mulss xmm5, dword ptr [r8 + 36]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 404], xmm4",
        "movss xmm4, dword ptr [r8 + 8]",
        "mulss xmm4, xmm0",
        "mulss xmm0, dword ptr [r8 + 12]",
        "movaps xmm5, xmm3",
        "mulss xmm5, dword ptr [r8 + 56]",
        "mulss xmm3, dword ptr [r8 + 60]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 24]",
        "mulss xmm1, dword ptr [r8 + 28]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm2",
        "mulss xmm5, dword ptr [r8 + 40]",
        "mulss xmm2, dword ptr [r8 + 44]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 408], xmm4",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r9 + 292]",
        "addss xmm0, xmm2",
        "addss xmm0, xmm3",
        "movss dword ptr [r9 + 412], xmm0",
        "movss xmm0, dword ptr [r9 + 288]",
        "movaps xmm4, xmm0",
        "mulss xmm4, dword ptr [r8 + 0]",
        "movaps xmm2, xmm1",
        "mulss xmm2, dword ptr [r8 + 16]",
        "addss xmm4, xmm2",
        "movss xmm2, dword ptr [r9 + 296]",
        "movaps xmm3, xmm2",
        "mulss xmm3, dword ptr [r8 + 32]",
        "addss xmm4, xmm3",
        "movss xmm3, dword ptr [r9 + 300]",
        "movaps xmm5, xmm3",
        "mulss xmm5, dword ptr [r8 + 48]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 416], xmm4",
        "movss xmm4, dword ptr [r8 + 52]",
        "mulss xmm4, xmm3",
        "movaps xmm5, xmm0",
        "mulss xmm5, dword ptr [r8 + 4]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 20]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm2",
        "mulss xmm5, dword ptr [r8 + 36]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 420], xmm4",
        "movss xmm4, dword ptr [r8 + 8]",
        "mulss xmm4, xmm0",
        "mulss xmm0, dword ptr [r8 + 12]",
        "movaps xmm5, xmm3",
        "mulss xmm5, dword ptr [r8 + 56]",
        "addss xmm4, xmm5",
        "mulss xmm3, dword ptr [r8 + 60]",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 24]",
        "mulss xmm1, dword ptr [r8 + 28]",
        "addss xmm4, xmm5",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r9 + 308]",
        "movaps xmm5, xmm2",
        "mulss xmm5, dword ptr [r8 + 40]",
        "mulss xmm2, dword ptr [r8 + 44]",
        "addss xmm4, xmm5",
        "addss xmm0, xmm2",
        "addss xmm0, xmm3",
        "movss dword ptr [r9 + 424], xmm4",
        "movss dword ptr [r9 + 428], xmm0",
        "movss xmm0, dword ptr [r9 + 304]",
        "movaps xmm4, xmm0",
        "mulss xmm4, dword ptr [r8 + 0]",
        "movaps xmm2, xmm1",
        "mulss xmm2, dword ptr [r8 + 16]",
        "addss xmm4, xmm2",
        "movss xmm2, dword ptr [r9 + 312]",
        "movaps xmm3, xmm2",
        "mulss xmm3, dword ptr [r8 + 32]",
        "addss xmm4, xmm3",
        "movss xmm3, dword ptr [r9 + 316]",
        "movaps xmm5, xmm3",
        "mulss xmm5, dword ptr [r8 + 48]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 432], xmm4",
        "movss xmm4, dword ptr [r8 + 52]",
        "movaps xmm5, xmm0",
        "mulss xmm5, dword ptr [r8 + 4]",
        "mulss xmm4, xmm3",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 20]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm2",
        "mulss xmm5, dword ptr [r8 + 36]",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 436], xmm4",
        "movss xmm4, dword ptr [r8 + 8]",
        "mulss xmm4, xmm0",
        "mulss xmm0, dword ptr [r8 + 12]",
        "movaps xmm5, xmm3",
        "mulss xmm5, dword ptr [r8 + 56]",
        "mulss xmm3, dword ptr [r8 + 60]",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm1",
        "mulss xmm5, dword ptr [r8 + 24]",
        "mulss xmm1, dword ptr [r8 + 28]",
        "addss xmm0, xmm1",
        "addss xmm4, xmm5",
        "movaps xmm5, xmm2",
        "mulss xmm2, dword ptr [r8 + 44]",
        "mulss xmm5, dword ptr [r8 + 40]",
        "addss xmm0, xmm2",
        "addss xmm0, xmm3",
        "movss dword ptr [r9 + 444], xmm0",
        "addss xmm4, xmm5",
        "movss dword ptr [r9 + 440], xmm4",
        in("r8") state.as_ptr(), in("r9") scratch.as_mut_ptr(),
        out("xmm0") _,
        out("xmm1") _,
        out("xmm2") _,
        out("xmm3") _,
        out("xmm4") _,
        out("xmm5") _,
        out("xmm6") _,
        out("xmm7") _,
        options(nostack)
    ); }
}
unsafe fn object_camera(state: &[u32; 60], scratch: &mut [u32; 384]) {
    unsafe { core::arch::asm!(
        "movss xmm0, dword ptr [r8 + 44]",
        "mulss xmm0, dword ptr [r8 + 108]",
        "movss xmm1, dword ptr [r8 + 56]",
        "mulss xmm1, dword ptr [r8 + 156]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 52]",
        "mulss xmm1, dword ptr [r8 + 140]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 48]",
        "mulss xmm1, dword ptr [r8 + 124]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 144]",
        "mulss xmm1, dword ptr [r8 + 52]",
        "movss dword ptr [r9 + 64], xmm0",
        "movss xmm0, dword ptr [r8 + 44]",
        "mulss xmm0, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 48]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 160]",
        "mulss xmm1, dword ptr [r8 + 56]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 56]",
        "mulss xmm1, dword ptr [r8 + 164]",
        "movss dword ptr [r9 + 68], xmm0",
        "movss xmm0, dword ptr [r8 + 132]",
        "mulss xmm0, dword ptr [r8 + 48]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 52]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 44]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 48]",
        "movss dword ptr [r9 + 72], xmm0",
        "movss xmm0, dword ptr [r8 + 120]",
        "mulss xmm0, dword ptr [r8 + 44]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 56]",
        "mulss xmm1, dword ptr [r8 + 168]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 52]",
        "mulss xmm1, dword ptr [r8 + 152]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 156]",
        "mulss xmm1, dword ptr [r8 + 72]",
        "movss dword ptr [r9 + 76], xmm0",
        "movss xmm0, dword ptr [r8 + 124]",
        "mulss xmm0, dword ptr [r8 + 64]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 68]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 60]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 144]",
        "mulss xmm1, dword ptr [r8 + 68]",
        "movss dword ptr [r9 + 80], xmm0",
        "movss xmm0, dword ptr [r8 + 160]",
        "mulss xmm0, dword ptr [r8 + 72]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 64]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 60]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 68]",
        "movss dword ptr [r9 + 84], xmm0",
        "movss xmm0, dword ptr [r8 + 164]",
        "mulss xmm0, dword ptr [r8 + 72]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 60]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 132]",
        "mulss xmm1, dword ptr [r8 + 64]",
        "addss xmm0, xmm1",
        "movss dword ptr [r9 + 88], xmm0",
        "movss xmm0, dword ptr [r8 + 120]",
        "mulss xmm0, dword ptr [r8 + 60]",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 72]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 68]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 64]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 156]",
        "mulss xmm1, dword ptr [r8 + 88]",
        "movss dword ptr [r9 + 92], xmm0",
        "movss xmm0, dword ptr [r8 + 124]",
        "mulss xmm0, dword ptr [r8 + 80]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 84]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 76]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 144]",
        "mulss xmm1, dword ptr [r8 + 84]",
        "movss dword ptr [r9 + 96], xmm0",
        "movss xmm0, dword ptr [r8 + 160]",
        "mulss xmm0, dword ptr [r8 + 88]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 80]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 76]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 84]",
        "movss dword ptr [r9 + 100], xmm0",
        "movss xmm0, dword ptr [r8 + 164]",
        "mulss xmm0, dword ptr [r8 + 88]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 76]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 132]",
        "mulss xmm1, dword ptr [r8 + 80]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 88]",
        "movss dword ptr [r9 + 104], xmm0",
        "movss xmm0, dword ptr [r8 + 120]",
        "mulss xmm0, dword ptr [r8 + 76]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 84]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 80]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 156]",
        "mulss xmm1, dword ptr [r8 + 104]",
        "movss dword ptr [r9 + 108], xmm0",
        "movss xmm0, dword ptr [r8 + 124]",
        "mulss xmm0, dword ptr [r8 + 96]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 140]",
        "mulss xmm1, dword ptr [r8 + 100]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 92]",
        "mulss xmm1, dword ptr [r8 + 108]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 144]",
        "mulss xmm1, dword ptr [r8 + 100]",
        "movss dword ptr [r9 + 112], xmm0",
        "movss xmm0, dword ptr [r8 + 160]",
        "mulss xmm0, dword ptr [r8 + 104]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 96]",
        "mulss xmm1, dword ptr [r8 + 128]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 92]",
        "mulss xmm1, dword ptr [r8 + 112]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 148]",
        "mulss xmm1, dword ptr [r8 + 100]",
        "movss dword ptr [r9 + 116], xmm0",
        "movss xmm0, dword ptr [r8 + 164]",
        "mulss xmm0, dword ptr [r8 + 104]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 92]",
        "mulss xmm1, dword ptr [r8 + 116]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 132]",
        "mulss xmm1, dword ptr [r8 + 96]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 168]",
        "mulss xmm1, dword ptr [r8 + 104]",
        "movss dword ptr [r9 + 120], xmm0",
        "movss xmm0, dword ptr [r8 + 120]",
        "mulss xmm0, dword ptr [r8 + 92]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 152]",
        "mulss xmm1, dword ptr [r8 + 100]",
        "addss xmm0, xmm1",
        "movss xmm1, dword ptr [r8 + 136]",
        "mulss xmm1, dword ptr [r8 + 96]",
        "addss xmm0, xmm1",
        "movss dword ptr [r9 + 124], xmm0",
        in("r8") state.as_ptr(), in("r9") scratch.as_mut_ptr(),
        out("xmm0") _,
        out("xmm1") _,
        out("xmm2") _,
        out("xmm3") _,
        out("xmm4") _,
        out("xmm5") _,
        out("xmm6") _,
        out("xmm7") _,
        options(nostack)
    ); }
}
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<_> = env::args_os().collect(); if args.len()!=3 {return Err("usage: probe INPUT OUTPUT".into());}
    let input=fs::read(&args[1])?; if input.len()%192!=0 {return Err("Invalid matrices".into());}
    let mut saved=0u32; let control=0x1f80u32;
    unsafe {core::arch::asm!("stmxcsr [{old}]", "ldmxcsr [{new}]", old=in(reg)&mut saved, new=in(reg)&control, options(nostack));}
    let mut output=vec![];
    for record in input.chunks_exact(192) {
        let mut state=[0u32;60]; for (i,word) in record.chunks_exact(4).enumerate() {state[11+i]=u32::from_le_bytes(word.try_into().unwrap());}
        let mut scratch=[0u32;384];
        unsafe { world_screen(&state,&mut scratch); }
        let world: [u32;16]=scratch[160..176].try_into().unwrap();
        unsafe { object_screen_view(&state,&mut scratch); }
        let view: [u32;16]=scratch[192..208].try_into().unwrap(); scratch[64..80].copy_from_slice(&view);
        let mut projection=[0u32;60]; projection[..16].copy_from_slice(&state[43..59]);
        unsafe { object_screen_projection(&projection,&mut scratch); }
        let screen: [u32;16]=scratch[96..112].try_into().unwrap();
        unsafe { object_camera(&state,&mut scratch); }
        let camera: [u32;16]=scratch[16..32].try_into().unwrap();
        for matrix in [world,screen,camera] { for col in 0..4 { for row in 0..4 {output.extend_from_slice(&matrix[row*4+col].to_le_bytes());} } }
    }
    unsafe {core::arch::asm!("ldmxcsr [{old}]", old=in(reg)&saved, options(nostack));}
    fs::write(&args[2],output)?; Ok(())
}
