"""Cross-check every StaticInit AllocateNameEntry against PE strings and assembly operands."""
from pathlib import Path
import hashlib
import json
import re
import struct
import sys

root = Path(__file__).resolve().parents[1]
binary = Path(r"D:\SteamLibrary\steamapps\common\Star Wars Republic Commando\GameData\System\core.dll")
data = binary.read_bytes()
pe = struct.unpack_from("<I", data, 60)[0]
assert data[:2] == b"MZ" and data[pe:pe+4] == b"PE\0\0"
optional = pe + 24
assert struct.unpack_from("<H",data,optional)[0] == 0x10b
base = struct.unpack_from("<I",data,optional+28)[0]
count = struct.unpack_from("<H",data,pe+6)[0]
size = struct.unpack_from("<H",data,pe+20)[0]
sections = [struct.unpack_from("<IIII",data,optional+size+i*40+8) for i in range(count)]
def offset(address):
    rva = address-base
    found = [raw+rva-start for _,start,size,raw in sections if start<=rva<start+size]
    assert len(found)==1
    return found[0]
def string(address):
    start = offset(address)
    end = data.index(0,start,start+256)
    return data[start:end].decode("ascii")

asm = (root/"analysis/decompiled/name-static-init.asm").read_text()
entries = []
ecx = edx = None
pending = None
for line in asm.splitlines():
    instruction = line.partition(" ")[2]
    match = re.fullmatch(r"MOV (ECX|EDX),(0x[0-9a-f]+)",instruction)
    if match:
        value = int(match[2],16)
        start = offset(int(line.split()[0],16))
        opcode = b"\xb9" if match[1]=="ECX" else b"\xba"
        assert data[start:start+5] == opcode + struct.pack("<I",value)
        if match[1]=="ECX": ecx=value
        else: edx=value
    elif instruction=="XOR EDX,EDX": edx=0
    elif instruction=="CALL 0x1014f880":
        address = int(line.split()[0],16)
        start = offset(address)
        assert data[start] == 0xe8 and address+5+struct.unpack_from("<i",data,start+1)[0] == 0x1014f880
        assert ecx is not None and edx is not None and pending is None
        pending = {"index":edx,"name":string(ecx),"string_va":f"{ecx:08x}","string_file_offset":offset(ecx),"allocate_call_va":line.split()[0]}
        ecx=edx=None
    elif instruction=="CALL 0x10150390":
        address = int(line.split()[0],16)
        start = offset(address)
        assert data[start] == 0xe8 and address+5+struct.unpack_from("<i",data,start+1)[0] == 0x10150390
        assert pending is not None
        pending["hardcode_call_va"]=line.split()[0]
        entries.append(pending)
        pending=None
assert pending is None
decompiled = (root/"analysis/decompiled/name-registration.c").read_text()
calls = re.findall(r'AllocateNameEntry\("([^"\\]*)",(0x[0-9a-f]+|[0-9]+),0x[0-9a-f]+,\(FNameEntry \*\)0x0\)',decompiled)
assert [(e["name"],e["index"]) for e in entries] == [(name,int(index,0)) for name,index in calls]
assert len({e["index"] for e in entries})==len(entries)
assert len({e["name"].lower() for e in entries})==len(entries)
notify = next(e for e in entries if e["name"]=="NotifyHitWall")
assert notify["index"] == 353
generated = "// Generated by scripts/Verify-HardcodedNames.py from verified core.dll StaticInit.\n"
generated += "pub const HARDCODED_NAMES: &[(i32, &str)] = &[\n"
generated += "".join(f"    ({e['index']}, {json.dumps(e['name'])}),\n" for e in entries)
generated += "];\n"
target = root/"crates/rc-package/src/hardcoded_names.rs"
if "--write" in sys.argv:
    target.write_text(generated,encoding="utf-8")
else:
    assert target.read_text(encoding="utf-8")==generated
result = {"date":"2026-10-07","core_dll_sha256":hashlib.sha256(data).hexdigest(),"entries":entries,
          "count":len(entries),"maximum_fixed_index":max(e["index"] for e in entries),
          "notify_hit_wall":{"index":353,"mask_bit":53,"mask_hex":f"{1<<53:016x}","struct_hash_bucket":353&127},
          "scope":"Fixed StaticInit indices verified with assembly operands and raw PE strings. FName entry pointers are runtime allocations, not string VAs. Dynamic indices depend on allocation/load/purge order."}
(root/"analysis/reports/hardcoded-names-proof.json").write_text(json.dumps(result,indent=2)+"\n",encoding="utf-8")
print(json.dumps({k:result[k] for k in ("count","maximum_fixed_index","notify_hit_wall")}))
